### PR TITLE
Add svg animation on landing page

### LINKED ISSUE #61: Animation for the landing page

### PR DESCRIPTION
**Pull request by MayeulC**
Fixes #61

I am not the best webdev there is, especially when it comes to aesthetics. Not sure where to position the image, so please give me some feedback.

I added a `<style>` element as a fallback when javascript is disabled and the image is loaded externally.

### CODE REVIEW

**Comment by karmanyaahm** [comment]
How about this?
https://github.com/karmanyaahm/documentation/commit/116c4eb22efdb741d179755708de5c10760bffd1
It makes the image fill match the font color set by the theme.

**Comment by karmanyaahm** [comment]
And this? https://github.com/karmanyaahm/documentation/commit/321e98828e471ca38637155a5177f1da9739a283
Also, on no js, setting the background color of the object black is visually an easy fix to make things legible, but it looks out of context.

**Comment by MayeulC** [comment]
Woops, I couldn't make sense out of what you wrote, but it turns out I forgot to add the svg :P

I intended for some of the css you wrote to be inside the svg, as you can see. This can be changed, however, I don't have strong feeling, except that I don't really like having `!important`. I am not sure about adding a class to the element in javascript, it sounds simpler to create a class, and have the object as a child.

I also set the default svg background to the same one as the website, that way it works better without javascript.

**Comment by karmanyaahm** [comment]
At least on my browser, not closing the object with `</object>` explicitly, hides the remainder of the page. 
image

Other than that, I'm good with merging this.

**Comment by karmanyaahm** [comment]
Also, we don't need a class anymore now that the css is inside the svg.

**Comment by MayeulC** [comment]
> not closing the object with </object> explicitly, hides the remainder of the page.

Thanks for spotting this, that's a mistake on my side, I inserted the object in the html to test, and copy-pasted it in the markdown without the closing tag, without testing further.

**Pull request merged**
