### PR TITLE
Create unified-push-xmpp

### PR DESCRIPTION
**Pull request by poVoq**

### CODE REVIEW

**Comment by karmanyaahm** [comment]
@genofire https://dev.sum7.eu/genofire/unified-push-xmpp is not complete yet, right?

**Comment by poVoq** [comment]
I have not actually tried it yet.

**Comment by genofire** [comment]
> @genofire https://dev.sum7.eu/genofire/unified-push-xmpp is not complete yet, right?

It works with a few bugs
- reconnect is the worst

**Comment by poVoq** [comment]
Great. Good to know. Could you also specify a license?

**Comment by genofire** [comment]
oh yes, i have to publish one.

planned is AGPL but mellium is a little bit complex:
https://github.com/mellium/xmpp/blob/main/LICENSE

**Comment by p1gp1g** [comment]
Before merging, we should:
* update the license,
* add the alpha or beta status 
* add that it targets linux devices

**Pull request closed without merging**
