### PR TITLE
Add Neon

### PR DESCRIPTION
**Pull request by provokateurin**
Closes https://github.com/nextcloud/neon/issues/752
What is the purpose of the Date column? Is it the date when the app was added?
Secondly, our app has no release yet, but supports UP since the beginning. Is `Unreleased` fine if we update it once we have a first release?

### CODE REVIEW

**Comment by p1gp1g** [comment]
It's OK if it is unreleased. The date is that of the first (beta) version supporting UP. You can set the date when UP was supported by neon, since it hasn't been released yet :)

**Comment by provokateurin** [comment]
Done!

**Comment by p1gp1g** [comment]
Do you mind putting it after smalltalk ? So this list is chronological ?

**Comment by p1gp1g** [comment]
Thanks :)

**Pull request merged**
